name: wetter
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - python=3.10
  - setuptools=61.2
  - numpy=1.25
  - pandas=1.5
  - ipykernel=6.15
  - black=23.3
  - black-jupyter=23.3
  - pylint=2.16
  - pytest=7.3
  - notebook
  - colorama=0.4
  - requests=2.31
