"""Constants for the forecast module."""

AVG_TEMP_C = "avgtemp_c"
CONDITION_DESC = "condition"
CURRENT_WEATHER = "current"
DAILY_CHANCE_OF_RAIN = "daily_chance_of_rain"
DATE = "date"
DAY = "day"
HOURS = "hour"
LOCATION = "location"
MAX_TEMP_C = "maxtemp_c"
MAX_WIND_KPH = "maxwind_kph"
MIN_TEMP_C = "mintemp_c"
NAME = "name"
TEMP_C = "temp_c"
TEMP_FEELS_LIKE_C = "feelslike_c"
TEXT_DESC = "text"
WIND_KPH = "wind_kph"
FORECAST = "forecast"
FORECAST_DAY = "forecastday"
