URL_BASE = "http://api.weatherapi.com/v1"
CURRENT_WEATHER_ENDPOINT = "/current.json"
FORECAST_ENDPOINT = "/forecast.json"

CURRENT_WEATHER_URL = URL_BASE + CURRENT_WEATHER_ENDPOINT
FORECAST_URL = URL_BASE + FORECAST_ENDPOINT